services:
  - type: web
    name: servicios-medicos
    env: python
    plan: free  # puedes cambiar a "starter" si necesitas más RAM
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 2 --timeout 180
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: FLASK_ENV
        value: production
